# Generated by Django 6.0.2 on 2026-02-10 05:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_mail', models.EmailField(max_length=100, unique=True)),
                ('user_password_hash', models.CharField(max_length=128)),
                ('user_surname', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('user_patronymic', models.CharField(blank=True, max_length=100, null=True)),
                ('user_phone', models.CharField(max_length=11)),
                ('user_dilivery_address', models.TextField(blank=True, null=True)),
                ('user_role', models.CharField(choices=[('User', 'Пользователь'), ('Manager', 'Менеджер'), ('Admin', 'Администратор')], default='User', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_title', models.CharField(max_length=60)),
                ('category_description', models.TextField(blank=True, null=True)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_title', models.TextField()),
                ('product_description', models.TextField(blank=True, null=True)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('product_quantity_in_stock', models.IntegerField()),
                ('product_image_url', models.URLField(blank=True, max_length=255, null=True)),
                ('product_brand_title', models.CharField(blank=True, max_length=50, null=True)),
                ('product_date_of_create', models.DateTimeField(default=django.utils.timezone.now)),
                ('product_is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category')),
            ],
        ),
    ]
