# Generated by Django 6.0.2 on 2026-02-10 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_user_customuser_alter_category_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_dilivery_address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_phone',
        ),
    ]
