# Generated by Django 6.0.2 on 2026-02-28 06:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_customuser_user_dilivery_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('basket_id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='basket', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'basket',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_create', models.DateTimeField(auto_now_add=True)),
                ('order_status', models.CharField(choices=[('В обработке', 'В обработке'), ('Собирается', 'Собирается'), ('Собран', 'Собран'), ('В пути', 'В пути'), ('Доставлен', 'Доставлен'), ('Отменён', 'Отменён')], default='В обработке', max_length=20)),
                ('delivery_address', models.TextField()),
                ('payment_method', models.CharField(choices=[('Онлайн', 'Онлайн'), ('Наличными', 'Наличными')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('user_comment', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'order',
                'ordering': ['-date_of_create'],
            },
        ),
        migrations.CreateModel(
            name='OrderPosition',
            fields=[
                ('order_position_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_quantity', models.IntegerField(default=1)),
                ('product_price_in_moment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='main.order')),
                ('product', models.ForeignKey(db_column='product_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.product')),
            ],
            options={
                'db_table': 'order_position',
            },
        ),
        migrations.CreateModel(
            name='BasketPosition',
            fields=[
                ('basket_position_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('basket', models.ForeignKey(db_column='basket_id', on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='main.basket')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='main.product')),
            ],
            options={
                'db_table': 'basket_position',
                'unique_together': {('basket', 'product')},
            },
        ),
    ]
